# Generated by Django 4.1.3 on 2022-12-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigi', '0002_alter_feature_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('large', 'LARGE')], default='small', max_length=5),
        ),
    ]
