# Generated by Django 4.1.3 on 2022-12-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigi', '0005_rename_shippingaddres_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='customer', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='collection', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(default='features', max_length=255),
        ),
    ]
