# Generated by Django 4.1.3 on 2022-12-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigi', '0006_customer_slug_alter_collection_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
